
package org.apache.fineract.CreditCheck.equifax.services.eport.servicedefs._1;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

import org.apache.fineract.CreditCheck.equifax.services.eport.ws.schemas._1.InquiryRequestType;
import org.apache.fineract.CreditCheck.equifax.services.eport.ws.schemas._1.InquiryResponseType;

import org.apache.fineract.CreditCheck.equifax.services.eport.ws.schemas._1.ObjectFactory;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CreditReportWSInquiryPortType", targetNamespace = "http://services.equifax.com/eport/servicedefs/1.0")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CreditReportWSInquiryPortType {


    /**
     * 
     * @param input
     * @return
     *     returns com.equifax.services.eport.ws.schemas._1.InquiryResponseType
     */
    @WebMethod(action = "http://services.equifax.com/CreditReportWS/CreditReportWSInquiry/1.0")
    @WebResult(name = "InquiryResponse", targetNamespace = "http://services.equifax.com/eport/ws/schemas/1.0", partName = "Output")
    public InquiryResponseType getConsumerCreditReport(
        @WebParam(name = "InquiryRequest", targetNamespace = "http://services.equifax.com/eport/ws/schemas/1.0", partName = "Input")
        InquiryRequestType input);

}
