/**
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements. See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership. The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied. See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
package org.apache.fineract.CreditCheck.equifax.services.eport.servicedefs._1;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

import org.apache.fineract.CreditCheck.equifax.services.eport.ws.schemas._1.InquiryRequestType;
import org.apache.fineract.CreditCheck.equifax.services.eport.ws.schemas._1.InquiryResponseType;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CreditReportWSInquiryPortType", targetNamespace = "http://services.equifax.com/eport/servicedefs/1.0")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
/*@XmlSeeAlso({
    ObjectFactory.class
})*/
public interface CreditReportWSInquiryPortType {


    /**
     * 
     * @param input
     * @return
     *     returns com.equifax.services.eport.ws.schemas._1.InquiryResponseType
     */
    @WebMethod(action = "http://services.equifax.com/CreditReportWS/CreditReportWSInquiry/1.0")
    @WebResult(name = "InquiryResponse", targetNamespace = "http://services.equifax.com/eport/ws/schemas/1.0", partName = "Output")
    public InquiryResponseType getConsumerCreditReport(
        @WebParam(name = "InquiryRequest", targetNamespace = "http://services.equifax.com/eport/ws/schemas/1.0", partName = "Input")
        InquiryRequestType input);

}
