
package org.apache.fineract.CreditCheck.equifax.services.eport.servicedefs._1;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "v1.0", targetNamespace = "http://services.equifax.com/eport/servicedefs/1.0", wsdlLocation = "https://eport.equifax.co.in/creditreportws/CreditReportWSInquiry/v1.0?wsdl")
public class V10
    extends Service
{

    private final static URL V10_WSDL_LOCATION;
    private final static WebServiceException V10_EXCEPTION;
    private final static QName V10_QNAME = new QName("http://services.equifax.com/eport/servicedefs/1.0", "v1.0");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://eport.equifax.co.in/creditreportws/CreditReportWSInquiry/v1.0?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        V10_WSDL_LOCATION = url;
        V10_EXCEPTION = e;
    }

    public V10() {
        super(__getWsdlLocation(), V10_QNAME);
    }

    public V10(WebServiceFeature... features) {
        super(__getWsdlLocation(), V10_QNAME, features);
    }

    public V10(URL wsdlLocation) {
        super(wsdlLocation, V10_QNAME);
    }

    public V10(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, V10_QNAME, features);
    }

    public V10(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public V10(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CreditReportWSInquiryPortType
     */
    @WebEndpoint(name = "CreditReportWSInquiryPort")
    public CreditReportWSInquiryPortType getCreditReportWSInquiryPort() {
        return super.getPort(new QName("http://services.equifax.com/eport/servicedefs/1.0", "CreditReportWSInquiryPort"), CreditReportWSInquiryPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CreditReportWSInquiryPortType
     */
    @WebEndpoint(name = "CreditReportWSInquiryPort")
    public CreditReportWSInquiryPortType getCreditReportWSInquiryPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://services.equifax.com/eport/servicedefs/1.0", "CreditReportWSInquiryPort"), CreditReportWSInquiryPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (V10_EXCEPTION!= null) {
            throw V10_EXCEPTION;
        }
        return V10_WSDL_LOCATION;
    }

}
